-- This file is generated by pnpm db:schema. Do not edit manually.

CREATE TABLE itinerary_secrets (
  itinerary_id TEXT PRIMARY KEY,
  enabled BOOLEAN DEFAULT FALSE,
  offset_minutes INTEGER DEFAULT 60,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "itineraries" (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  theme_id TEXT NOT NULL DEFAULT 'standard-autumn',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  memo TEXT,
  password TEXT
, source_itinerary_id TEXT, packing_enabled INTEGER NOT NULL DEFAULT 1 CHECK(packing_enabled IN (0, 1)), prefecture_slugs TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(prefecture_slugs)), areas TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(areas)), tags TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(tags)), metadata_initialized INTEGER NOT NULL DEFAULT 1 CHECK(metadata_initialized IN (0, 1)), palette_id TEXT NOT NULL DEFAULT 'sakura');
CREATE TABLE IF NOT EXISTS "steps" (
  id TEXT PRIMARY KEY,
  itinerary_id TEXT NOT NULL,
  title TEXT NOT NULL,
  start_at INTEGER NOT NULL,
  end_at INTEGER NOT NULL,
  location TEXT,
  notes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'normal:general', is_all_day INTEGER NOT NULL DEFAULT 0, link TEXT,
  FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE
);
CREATE INDEX idx_steps_start_at ON steps(itinerary_id, start_at);
CREATE INDEX idx_steps_end_at ON steps(itinerary_id, end_at);
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
, prefecture TEXT, email_verified_at TEXT);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);
CREATE TABLE user_bookmarks (
  user_id TEXT NOT NULL,
  itinerary_id TEXT NOT NULL,
  is_visible INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL, prefecture_slugs TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(prefecture_slugs)), areas TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(areas)), tags TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(tags)),
  PRIMARY KEY (user_id, itinerary_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE
);
CREATE INDEX idx_user_bookmarks_user_id ON user_bookmarks(user_id);
CREATE INDEX idx_user_bookmarks_itinerary_id ON user_bookmarks(itinerary_id);
CREATE INDEX idx_itineraries_created_at ON itineraries(created_at DESC);
CREATE TABLE itinerary_favorites (
  user_id TEXT NOT NULL,
  itinerary_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (user_id, itinerary_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE
);
CREATE INDEX idx_itinerary_favorites_user_id ON itinerary_favorites(user_id);
CREATE INDEX idx_itinerary_favorites_itinerary_id ON itinerary_favorites(itinerary_id);
CREATE TABLE itinerary_fork_stats (
  itinerary_id TEXT PRIMARY KEY,
  fork_count INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX idx_itineraries_source_id ON itineraries(source_itinerary_id) WHERE source_itinerary_id IS NOT NULL;
CREATE TABLE itinerary_money_settings (
  itinerary_id TEXT PRIMARY KEY,
  budget_amount INTEGER,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE
);
CREATE TABLE itinerary_members (
  id TEXT PRIMARY KEY,
  itinerary_id TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE
);
CREATE INDEX idx_itinerary_members_itinerary
  ON itinerary_members(itinerary_id, created_at);
CREATE INDEX idx_users_verified ON users(email_verified_at);
CREATE TABLE itinerary_packing_groups (
  id TEXT PRIMARY KEY,
  itinerary_id TEXT NOT NULL,
  name TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE
);
CREATE INDEX idx_packing_groups_itinerary
  ON itinerary_packing_groups(itinerary_id, sort_order, created_at);
CREATE UNIQUE INDEX idx_itinerary_members_id_itinerary
  ON itinerary_members(id, itinerary_id);
CREATE UNIQUE INDEX idx_steps_id_itinerary
  ON steps(id, itinerary_id);
CREATE UNIQUE INDEX idx_packing_groups_id_itinerary
  ON itinerary_packing_groups(id, itinerary_id);
CREATE TABLE itinerary_money_items (
  id TEXT PRIMARY KEY,
  itinerary_id TEXT NOT NULL,
  title TEXT NOT NULL,
  amount INTEGER NOT NULL CHECK(amount > 0),
  paid_by_member_id TEXT,
  status TEXT NOT NULL CHECK(status IN ('paid', 'planned')),
  occurred_on TEXT,
  step_id TEXT,
  is_settled INTEGER NOT NULL DEFAULT 0 CHECK(is_settled IN (0, 1)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL, paid_from_fund INTEGER NOT NULL DEFAULT 0 CHECK(paid_from_fund IN (0, 1)),
  FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE,
  FOREIGN KEY (paid_by_member_id, itinerary_id)
    REFERENCES itinerary_members(id, itinerary_id) ON DELETE RESTRICT,
  FOREIGN KEY (step_id) REFERENCES steps(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX idx_money_items_id_itinerary
  ON itinerary_money_items(id, itinerary_id);
CREATE INDEX idx_money_items_itinerary
  ON itinerary_money_items(itinerary_id, status);
CREATE INDEX idx_money_items_step
  ON itinerary_money_items(itinerary_id, step_id);
CREATE TABLE itinerary_money_item_splits (
  item_id TEXT NOT NULL,
  member_id TEXT NOT NULL,
  itinerary_id TEXT NOT NULL, amount INTEGER CHECK(amount > 0),
  PRIMARY KEY (item_id, member_id),
  FOREIGN KEY (item_id, itinerary_id)
    REFERENCES itinerary_money_items(id, itinerary_id) ON DELETE CASCADE,
  FOREIGN KEY (member_id, itinerary_id)
    REFERENCES itinerary_members(id, itinerary_id) ON DELETE RESTRICT
);
CREATE INDEX idx_money_item_splits_member
  ON itinerary_money_item_splits(itinerary_id, member_id);
CREATE TABLE itinerary_packing_items (
  id TEXT PRIMARY KEY,
  itinerary_id TEXT NOT NULL,
  name TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('personal', 'private', 'shared')),
  group_id TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK(quantity > 0),
  assignee_member_id TEXT,
  owner_member_id TEXT,
  is_packed INTEGER NOT NULL DEFAULT 0 CHECK(is_packed IN (0, 1)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE,
  FOREIGN KEY (group_id, itinerary_id)
    REFERENCES itinerary_packing_groups(id, itinerary_id) ON DELETE RESTRICT,
  FOREIGN KEY (assignee_member_id) REFERENCES itinerary_members(id) ON DELETE SET NULL,
  FOREIGN KEY (owner_member_id, itinerary_id)
    REFERENCES itinerary_members(id, itinerary_id) ON DELETE CASCADE,
  CHECK(
    (kind = 'personal' AND assignee_member_id IS NULL AND owner_member_id IS NULL)
    OR (kind = 'private' AND assignee_member_id IS NULL AND owner_member_id IS NOT NULL)
    OR (kind = 'shared' AND owner_member_id IS NULL)
  )
);
CREATE UNIQUE INDEX idx_packing_items_id_itinerary
  ON itinerary_packing_items(id, itinerary_id);
CREATE INDEX idx_packing_items_itinerary
  ON itinerary_packing_items(itinerary_id, kind, created_at);
CREATE INDEX idx_packing_items_group
  ON itinerary_packing_items(itinerary_id, group_id, kind, created_at);
CREATE INDEX idx_packing_items_owner
  ON itinerary_packing_items(itinerary_id, owner_member_id, kind);
CREATE TABLE itinerary_packing_checks (
  item_id TEXT NOT NULL,
  member_id TEXT NOT NULL,
  itinerary_id TEXT NOT NULL,
  checked_at TEXT NOT NULL,
  PRIMARY KEY (item_id, member_id),
  FOREIGN KEY (item_id, itinerary_id)
    REFERENCES itinerary_packing_items(id, itinerary_id) ON DELETE CASCADE,
  FOREIGN KEY (member_id, itinerary_id)
    REFERENCES itinerary_members(id, itinerary_id) ON DELETE CASCADE
);
CREATE TRIGGER validate_itinerary_snapshot_insert
BEFORE INSERT ON itineraries
WHEN NEW.source_itinerary_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM itineraries WHERE id = NEW.source_itinerary_id)
BEGIN
  SELECT RAISE(ABORT, 'source itinerary does not exist');
END;
CREATE TRIGGER validate_itinerary_snapshot_update
BEFORE UPDATE OF source_itinerary_id ON itineraries
WHEN NEW.source_itinerary_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM itineraries WHERE id = NEW.source_itinerary_id)
BEGIN
  SELECT RAISE(ABORT, 'source itinerary does not exist');
END;
CREATE TRIGGER delete_published_snapshot_with_source
BEFORE DELETE ON itineraries
WHEN OLD.source_itinerary_id IS NULL
BEGIN
  DELETE FROM itineraries WHERE source_itinerary_id = OLD.id;
END;
CREATE TABLE itinerary_publications (
  source_itinerary_id TEXT NOT NULL,
  shared_itinerary_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  prefecture_slugs TEXT NOT NULL CHECK(json_valid(prefecture_slugs)),
  areas TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(areas)),
  tags TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(tags)),
  published_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (source_itinerary_id, user_id),
  FOREIGN KEY (source_itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE,
  FOREIGN KEY (shared_itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_itinerary_publications_user
  ON itinerary_publications(user_id, published_at DESC);
CREATE INDEX idx_itinerary_publications_published
  ON itinerary_publications(published_at DESC);
CREATE TABLE itinerary_money_fund_transactions (
  id TEXT PRIMARY KEY,
  itinerary_id TEXT NOT NULL,
  member_id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('contribution', 'refund')),
  amount INTEGER NOT NULL CHECK(amount > 0),
  note TEXT,
  occurred_on TEXT NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE,
  FOREIGN KEY (member_id, itinerary_id)
    REFERENCES itinerary_members(id, itinerary_id) ON DELETE RESTRICT
);
CREATE INDEX idx_money_fund_transactions_itinerary
  ON itinerary_money_fund_transactions(itinerary_id, occurred_on, created_at);
CREATE INDEX idx_money_fund_transactions_member
  ON itinerary_money_fund_transactions(itinerary_id, member_id);
