import { type DemoDataSet, now, getTimestamp, getEndTimestamp } from '../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '東京ガイドツアー',
      theme_id: 'map-only',
      memo: '{"text":"地図で見るスポット巡り"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '浅草寺',
        start_at: getTimestamp(0, '09:00'),
        end_at: getEndTimestamp(getTimestamp(0, '09:00'), 90),
        location: '東京都台東区浅草',
        notes: '{"text":"雷門の写真を撮ろう"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: 'スカイツリー',
        start_at: getTimestamp(0, '11:00'),
        end_at: getEndTimestamp(getTimestamp(0, '11:00'), 120),
        location: '東京都墨田区押上',
        notes: '{"text":"展望台からの眺めが最高"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '秋葉原',
        start_at: getTimestamp(0, '15:00'),
        end_at: getEndTimestamp(getTimestamp(0, '15:00'), 120),
        location: '東京都千代田区秋葉原',
        notes: '{"text":"電気街の買い物"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '渋谷スクランブル交差点',
        start_at: getTimestamp(0, '17:30'),
        end_at: getEndTimestamp(getTimestamp(0, '17:30'), 60),
        location: '東京都渋谷区渋谷',
        notes: '{"text":"有名な交差点を体験"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '六本木ヒルズ',
        start_at: getTimestamp(1, '10:00'),
        end_at: getEndTimestamp(getTimestamp(1, '10:00'), 120),
        location: '東京都港区六本木',
        notes: '{"text":"モダンな建築を見学"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-6',
        itinerary_id: 'demo',
        title: 'お台場',
        start_at: getTimestamp(1, '14:00'),
        end_at: getEndTimestamp(getTimestamp(1, '14:00'), 180),
        location: '東京都港区お台場',
        notes: '{"text":"レインボーブリッジの眺め"}',
        created_at: now,
        updated_at: now,
      },
    ],
  };
}
