import { type DemoDataSet, now, getDate } from '../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '東京ガイドツアー',
      theme_id: 'map-only',
      memo: '{"text":"地図で見るスポット巡り"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '浅草寺',
        date: getDate(0),
        time: '09:00',
        location: '東京都台東区浅草',
        notes: '{"text":"雷門の写真を撮ろう"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: 'スカイツリー',
        date: getDate(0),
        time: '11:00',
        location: '東京都墨田区押上',
        notes: '{"text":"展望台からの眺めが最高"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '秋葉原',
        date: getDate(0),
        time: '15:00',
        location: '東京都千代田区秋葉原',
        notes: '{"text":"電気街の買い物"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '渋谷スクランブル交差点',
        date: getDate(0),
        time: '17:30',
        location: '東京都渋谷区渋谷',
        notes: '{"text":"有名な交差点を体験"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '六本木ヒルズ',
        date: getDate(1),
        time: '10:00',
        location: '東京都港区六本木',
        notes: '{"text":"モダンな建築を見学"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-6',
        itinerary_id: 'demo',
        title: 'お台場',
        date: getDate(1),
        time: '14:00',
        location: '東京都港区お台場',
        notes: '{"text":"レインボーブリッジの眺め"}',
        created_at: now,
        updated_at: now,
      },
    ],
  };
}
