import { type DemoDataSet, now, getTimestamp, getEndTimestamp } from '../../types';
import { STEP_TYPE } from "@tabitabi/types";

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '秋の紅葉狩り旅',
      theme_id: 'standard-autumn',
      memo: '{"text":"紅葉シーズンは混雑するので早めの行動を！\\n\\n持ち物リスト\\n- カメラ\\n- 防寒具"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-allday',
        itinerary_id: 'demo',
        title: '紅葉祭り（終日）',
        start_at: getTimestamp(0, '00:00'),
        end_at: getTimestamp(0, '23:59'),
        location: '日光市内各所',
        notes: '{"text":"終日イベント開催中"}',
        is_all_day: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '日光東照宮参拝',
        start_at: getTimestamp(0, '09:00'),
        end_at: getEndTimestamp(getTimestamp(0, '09:00'), 150),
        location: '栃木県日光市',
        notes: '{"text":"世界遺産。紅葉と歴史的建築の組み合わせが美しい。"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: '湯滝観瀑',
        start_at: getTimestamp(0, '12:00'),
        end_at: getEndTimestamp(getTimestamp(0, '12:00'), 90),
        location: '奥日光',
        notes: '{"text":"紅葉に囲まれた滝の絶景"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2-transport',
        itinerary_id: 'demo',
        title: '湯滝から華厳滝へ移動',
        start_at: getTimestamp(0, '13:30'),
        end_at: getEndTimestamp(getTimestamp(0, '13:30'), 60),
        location: '中禅寺湖周辺',
        notes: '{"text":"バスでの移動を想定"}',
        type: STEP_TYPE.TRANSPORT_BUS,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '華厳滝',
        start_at: getTimestamp(0, '15:00'),
        end_at: getEndTimestamp(getTimestamp(0, '15:00'), 60),
        location: '中禅寺湖畔',
        notes: '{"text":"日本三大名瀑のひとつ"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-multiday',
        itinerary_id: 'demo',
        title: '温泉旅館宿泊',
        start_at: getTimestamp(0, '18:00'),
        end_at: getTimestamp(1, '10:00'),
        location: '日光温泉郷',
        notes: '{"text":"2日目の朝まで温泉宿でゆっくり"}',
        type: STEP_TYPE.NORMAL_HOTEL,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '中禅寺湖散策',
        start_at: getTimestamp(1, '10:00'),
        end_at: getEndTimestamp(getTimestamp(1, '10:00'), 120),
        location: '中禅寺湖',
        notes: '{"text":"遊覧船で紅葉を楽しむ"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '豆腐懐石料理',
        start_at: getTimestamp(1, '13:00'),
        end_at: getEndTimestamp(getTimestamp(1, '13:00'), 90),
        location: '日光市内',
        notes: '{"text":"日光名物の湯波料理を堪能"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-breakfast',
        itinerary_id: 'demo',
        title: '旅館の朝食',
        start_at: getTimestamp(1, '08:30'),
        end_at: getEndTimestamp(getTimestamp(1, '08:30'), 45),
        location: '日光温泉郷',
        notes: '{"text":"温泉宿泊時の朝食"}',
        type: STEP_TYPE.NORMAL_MEAL,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-concurrent1',
        itinerary_id: 'demo',
        title: '日光自然博物館',
        start_at: getTimestamp(0, '09:00'),
        end_at: getEndTimestamp(getTimestamp(0, '09:00'), 90),
        location: '奥日光',
        notes: '{"text":"大人向けの自然史展示"}',
        type: STEP_TYPE.NORMAL_SIGHTSEEING,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-concurrent2',
        itinerary_id: 'demo',
        title: 'ガイドツアー：東照宮',
        start_at: getTimestamp(0, '09:00'),
        end_at: getEndTimestamp(getTimestamp(0, '09:00'), 120),
        location: '栃木県日光市',
        notes: '{"text":"別コースのガイド付きツアーオプション"}',
        type: STEP_TYPE.NORMAL_SIGHTSEEING,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-ending',
        itinerary_id: 'demo',
        title: '帰路：日光から東京へ',
        start_at: getTimestamp(1, '15:00'),
        end_at: getEndTimestamp(getTimestamp(1, '15:00'), 120),
        location: '日光駅～東京駅',
        notes: '{"text":"電車で帰宅"}',
        type: STEP_TYPE.TRANSPORT_TRAIN,
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 720,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: '01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
