import { type DemoDataSet, now, getDate } from '../../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '秋の紅葉狩り旅',
      theme_id: 'standard-autumn',      memo: '{"text":"紅葉シーズンは混雑するので早めの行動を！\\n\\n持ち物リスト\\n- カメラ\\n- 防寒具"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '日光東照宮参拝',
        date: getDate(0),
        time: '09:00',
        location: '栃木県日光市',
        notes: '{"text":"世界遺産。紅葉と歴史的建築の組み合わせが美しい。"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: '湯滝観瀑',
        date: getDate(0),
        time: '12:00',
        location: '奥日光',
        notes: '{"text":"紅葉に囲まれた滝の絶景"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '華厳滝',
        date: getDate(0),
        time: '15:00',
        location: '中禅寺湖畔',
        notes: '{"text":"日本三大名瀑のひとつ"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '中禅寺湖散策',
        date: getDate(1),
        time: '10:00',
        location: '中禅寺湖',
        notes: '{"text":"遊覧船で紅葉を楽しむ"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '豆腐懐石料理',
        date: getDate(1),
        time: '13:00',
        location: '日光市内',
        notes: '{"text":"日光名物の湯波料理を堪能"}',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 60,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: '01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
