import { execFileSync } from 'node:child_process';
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { parseMigrationText } from '../../api/scripts/migration-format.mjs';

const dbRoot = resolve(import.meta.dirname, '..');
const migrationsDir = join(dbRoot, 'migrations', 'sql');
const schemaPath = join(dbRoot, 'schema.sql');
const directory = mkdtempSync(join(tmpdir(), 'tabitabi-schema-'));
const databasePath = join(directory, 'schema.sqlite');

try {
  const migrationFiles = readdirSync(migrationsDir)
    .filter((file) => /^\d+_.+\.sql$/.test(file))
    .sort()
    .map((file) => join(migrationsDir, file));
  const sql = migrationFiles
    .map((file) => parseMigrationText(readFileSync(file, 'utf8'), file).up)
    .join('\n\n');

  execFileSync('sqlite3', [databasePath], { input: 'PRAGMA foreign_keys = ON;\n' + sql, stdio: ['pipe', 'ignore', 'inherit'] });
  const schema = execFileSync('sqlite3', [databasePath, '.schema'], { encoding: 'utf8' });
  writeFileSync(schemaPath, `-- This file is generated by pnpm db:schema. Do not edit manually.\n\n${schema}`);
} finally {
  rmSync(directory, { recursive: true, force: true });
}
