import { type DemoDataSet, now, getTimestamp, getEndTimestamp } from '../../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '冬休みのスキー旅行',
      theme_id: 'standard-winter',
      memo: '{"text":"雪山でのアクティビティ！防寒対策をしっかり\\n\\n持ち物リスト\\n- スキーウェア\\n- 手袋\\n- ゴーグル\\n- カイロ"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      // 終日イベント（スノーフェスティバル）
      {
        id: 'demo-step-allday',
        itinerary_id: 'demo',
        title: '白馬スノーフェスティバル（終日）',
        start_at: getTimestamp(0, '00:00'),
        end_at: getTimestamp(0, '23:59'),
        location: '白馬村',
        notes: '{"text":"雪のイベントが一日中開催。雪だるまコンテストや花火大会も"}',
        is_all_day: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '長野新幹線で移動',
        start_at: getTimestamp(0, '08:00'),
        end_at: getEndTimestamp(getTimestamp(0, '08:00'), 120),
        location: '東京駅',
        notes: '{"text":"北陸新幹線で長野へ"}',
        type: 'transport:train',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-transport',
        itinerary_id: 'demo',
        title: '長野駅からスキー場へ移動',
        start_at: getTimestamp(0, '11:00'),
        end_at: getEndTimestamp(getTimestamp(0, '11:00'), 90),
        location: '白馬村へ',
        notes: '{"text":"バスでスキー場へ"}',
        type: 'transport:bus',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: 'スキー場のレッスン',
        start_at: getTimestamp(0, '13:00'),
        end_at: getEndTimestamp(getTimestamp(0, '13:00'), 180),
        location: '白馬村',
        notes: '{"text":"初心者向けレッスンを受ける"}',
        type: 'normal:sightseeing',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '温泉',
        start_at: getTimestamp(0, '18:00'),
        end_at: getEndTimestamp(getTimestamp(0, '18:00'), 90),
        location: '白馬温泉',
        notes: '{"text":"スキーの疲れを癒す"}',
        type: 'normal:sightseeing',
        created_at: now,
        updated_at: now,
      },
      // 複数日イベント（温泉宿宿泊）
      {
        id: 'demo-step-hotel',
        itinerary_id: 'demo',
        title: '白馬温泉宿宿泊',
        start_at: getTimestamp(0, '21:00'),
        end_at: getTimestamp(1, '08:00'),
        location: '白馬村',
        notes: '{"text":"雪景色を眺めながら温泉に浸かれる宿"}',
        type: 'normal:hotel',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '蕎麦打ち体験',
        start_at: getTimestamp(1, '10:00'),
        end_at: getEndTimestamp(getTimestamp(1, '10:00'), 120),
        location: '長野市',
        notes: '{"text":"信州名物の蕎麦を自分で作る"}',
        type: 'normal:sightseeing',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-lunch',
        itinerary_id: 'demo',
        title: '信州牛焼肉ランチ',
        start_at: getTimestamp(1, '12:30'),
        end_at: getEndTimestamp(getTimestamp(1, '12:30'), 90),
        location: '長野市',
        notes: '{"text":"地元の美味しいお肉を味わう"}',
        type: 'normal:meal',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '初詣参拝',
        start_at: getTimestamp(1, '14:00'),
        end_at: getEndTimestamp(getTimestamp(1, '14:00'), 90),
        location: '善光寺',
        notes: '{"text":"一年の無事を祈る"}',
        type: 'normal:sightseeing',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 720,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: '01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
