import { type DemoDataSet, now, getTimestamp, getEndTimestamp } from '../../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '冬休みのスキー旅行',
      theme_id: 'standard-winter',
      memo: '{"text":"雪山でのアクティビティ！防寒対策をしっかり\\n\\n持ち物リスト\\n- スキーウェア\\n- 手袋\\n- ゴーグル"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '長野新幹線で移動',
        start_at: getTimestamp(0, '08:00'),
        end_at: getEndTimestamp(getTimestamp(0, '08:00'), 120),
        location: '東京駅',
        notes: '{"text":"北陸新幹線で長野へ"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: 'スキー場のレッスン',
        start_at: getTimestamp(0, '13:00'),
        end_at: getEndTimestamp(getTimestamp(0, '13:00'), 180),
        location: '白馬村',
        notes: '{"text":"初心者向けレッスンを受ける"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '温泉',
        start_at: getTimestamp(0, '18:00'),
        end_at: getEndTimestamp(getTimestamp(0, '18:00'), 90),
        location: '白馬温泉',
        notes: '{"text":"スキーの疲れを癒す"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '蕎麦打ち体験',
        start_at: getTimestamp(1, '10:00'),
        end_at: getEndTimestamp(getTimestamp(1, '10:00'), 120),
        location: '長野市',
        notes: '{"text":"信州名物の蕎麦を自分で作る"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '初詣参拝',
        start_at: getTimestamp(1, '14:00'),
        end_at: getEndTimestamp(getTimestamp(1, '14:00'), 90),
        location: '善光寺',
        notes: '{"text":"一年の無事を祈る"}',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 720,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: '01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
