import { type DemoDataSet, now, getDate } from '../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '東京・日光・鎌倉の旅',
      theme_id: 'standard-seasons',
      memo: '{"text":"3日間の関東旅行。交通はSuicaが便利です。"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '浅草寺',
        date: getDate(0),
        time: '09:00',
        location: '台東区浅草',
        notes: '{"text":"雷門と仲見世通りを散策"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: '渋谷スクランブル交差点',
        date: getDate(0),
        time: '12:00',
        location: '渋谷区',
        notes: '{"text":"世界有数の繁華街"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '秋葉原電気街',
        date: getDate(0),
        time: '15:00',
        location: '千代田区',
        notes: '{"text":"最新の電化製品とアニメグッズ"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '日光東照宮',
        date: getDate(1),
        time: '10:00',
        location: '日光市',
        notes: '{"text":"世界遺産の豪華絢爛な建築"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '中禅寺湖',
        date: getDate(1),
        time: '14:00',
        location: '日光市',
        notes: '{"text":"男体山を望む美しい湖"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-6',
        itinerary_id: 'demo',
        title: '高徳院（鎌倉大仏）',
        date: getDate(2),
        time: '09:30',
        location: '鎌倉市',
        notes: '{"text":"13.35mの露坐の大仏"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-7',
        itinerary_id: 'demo',
        title: '江の島',
        date: getDate(2),
        time: '13:00',
        location: '藤沢市',
        notes: '{"text":"島内散策と江の島岩屋"}',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: false,
      offset_minutes: 30,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: null,
  };
}
