import { type DemoDataSet, now, getTimestamp, getEndTimestamp } from '../../types';
import { STEP_TYPE } from "@tabitabi/types";

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '春休みの京都旅行',
      theme_id: 'standard-spring',
      memo: '{"text":"桜シーズンは混雑するので早めの行動を！\\n\\n持ち物リスト\\n- カメラ\\n- 日焼け止め\\n- 歩きやすい靴"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      // 終日イベント（桜祭り）
      {
        id: 'demo-step-allday',
        itinerary_id: 'demo',
        title: '祇園白川桜祭り（終日）',
        start_at: getTimestamp(0, '00:00'),
        end_at: getTimestamp(0, '23:59'),
        location: '祇園白川',
        notes: '{"text":"一日中桜のイベントが開催。夜桜ライトアップも"}',
        is_all_day: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '清水寺参拝',
        start_at: getTimestamp(0, '09:00'),
        end_at: getEndTimestamp(getTimestamp(0, '09:00'), 120),
        location: '京都市東山区',
        notes: '{"text":"桜の名所。清水の舞台からの眺めは絶景。"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: '祇園で懐石料理',
        start_at: getTimestamp(0, '12:00'),
        end_at: getEndTimestamp(getTimestamp(0, '12:00'), 90),
        location: '祇園',
        notes: '{"text":"京料理を堪能"}',
        type: STEP_TYPE.NORMAL_FOOD,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2-transport',
        itinerary_id: 'demo',
        title: '祇園から嵐山へ移動',
        start_at: getTimestamp(0, '13:30'),
        end_at: getEndTimestamp(getTimestamp(0, '13:30'), 60),
        location: '京都市内',
        notes: '{"text":"移動中：電車での移動を想定"}',
        type: STEP_TYPE.TRANSPORT_TRAIN,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '嵐山の桜散策',
        start_at: getTimestamp(0, '15:00'),
        end_at: getEndTimestamp(getTimestamp(0, '15:00'), 180),
        location: '嵐山',
        notes: '{"text":"竹林の小径と渡月橋を歩く"}',
        type: STEP_TYPE.NORMAL_SIGHTSEEING,
        created_at: now,
        updated_at: now,
      },
      // 複数日イベント（京都駅近くのホテル宿泊）
      {
        id: 'demo-step-hotel',
        itinerary_id: 'demo',
        title: '京都駅前ホテル宿泊',
        start_at: getTimestamp(0, '20:00'),
        end_at: getTimestamp(1, '09:00'),
        location: '京都駅前',
        notes: '{"text":"2日目の朝まで宿泊。朝食バイキング付き"}',
        type: STEP_TYPE.NORMAL_HOTEL,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '貴船神社の川沿い歩き',
        start_at: getTimestamp(1, '10:00'),
        end_at: getEndTimestamp(getTimestamp(1, '10:00'), 120),
        location: '貴船',
        notes: '{"text":"縁結びの神社。新緑と桜のコントラスト"}',
        type: STEP_TYPE.NORMAL_SIGHTSEEING,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-transport2',
        itinerary_id: 'demo',
        title: '貴船から哲学の道へ移動',
        start_at: getTimestamp(1, '12:30'),
        end_at: getEndTimestamp(getTimestamp(1, '12:30'), 90),
        location: '京都市内',
        notes: '{"text":"バスと徒歩での移動"}',
        type: STEP_TYPE.TRANSPORT_BUS,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '哲学の道散歩',
        start_at: getTimestamp(1, '14:00'),
        end_at: getEndTimestamp(getTimestamp(1, '14:00'), 90),
        location: '左京区',
        notes: '{"text":"桜のトンネルを歩く"}',
        type: STEP_TYPE.NORMAL_SIGHTSEEING,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-6',
        itinerary_id: 'demo',
        title: '伏見稲荷大社',
        start_at: getTimestamp(2, '09:00'),
        end_at: getEndTimestamp(getTimestamp(2, '09:00'), 150),
        location: '伏見区',
        notes: '{"text":"千本鳥居を散策"}',
        type: STEP_TYPE.NORMAL_SIGHTSEEING,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-7',
        itinerary_id: 'demo',
        title: '宇治の平等院鳳凰堂',
        start_at: getTimestamp(2, '13:00'),
        end_at: getEndTimestamp(getTimestamp(2, '13:00'), 120),
        location: '宇治市',
        notes: '{"text":"世界遺産を訪問。抹茶スイーツも楽しむ"}',
        type: STEP_TYPE.NORMAL_SIGHTSEEING,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-breakfast',
        itinerary_id: 'demo',
        title: '朝食：和定食（宿泊先）',
        start_at: getTimestamp(1, '08:30'),
        end_at: getEndTimestamp(getTimestamp(1, '08:30'), 45),
        location: '京都駅前',
        notes: '{"text":"ホテル宿泊時は朝食バイキング付き"}',
        type: STEP_TYPE.NORMAL_MEAL,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-concurrent1',
        itinerary_id: 'demo',
        title: '清水焼の絵付け体験',
        start_at: getTimestamp(0, '09:00'),
        end_at: getEndTimestamp(getTimestamp(0, '09:00'), 90),
        location: '五条坂',
        notes: '{"text":"陶芸体験。予約推奨"}',
        type: STEP_TYPE.NORMAL_SIGHTSEEING,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-concurrent2',
        itinerary_id: 'demo',
        title: 'ガイディングツアー：清水寺',
        start_at: getTimestamp(0, '09:00'),
        end_at: getEndTimestamp(getTimestamp(0, '09:00'), 120),
        location: '京都市東山区',
        notes: '{"text":"別ルートでのガイド付き参拝プランも可"}',
        type: STEP_TYPE.NORMAL_SIGHTSEEING,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-afternoon',
        itinerary_id: 'demo',
        title: '京都駅でお土産購入',
        start_at: getTimestamp(2, '15:30'),
        end_at: getEndTimestamp(getTimestamp(2, '15:30'), 60),
        location: '京都駅',
        notes: '{"text":"帰路前に京都限定のお菓子などを購入"}',
        type: STEP_TYPE.NORMAL_SHOPPING,
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 720,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: '01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
