import { type DemoDataSet, now, getDate } from '../../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '春休みの京都旅行',
      theme_id: 'standard-spring',
      memo: '{"text":"桜シーズンは混雑するので早めの行動を！\\n\\n持ち物リスト\\n- カメラ\\n- 日焼け止め"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '清水寺参拝',
        date: getDate(0),
        time: '09:00',
        location: '京都市東山区',
        notes: '{"text":"桜の名所。清水の舞台からの眺めは絶景。"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: '祇園で懐石料理',
        date: getDate(0),
        time: '12:00',
        location: '祇園',
        notes: '{"text":"京料理を堪能"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '嵐山の桜散策',
        date: getDate(0),
        time: '15:00',
        location: '嵐山',
        notes: '{"text":"竹林の小径と渡月橋を歩く"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '貴船神社の川沿い歩き',
        date: getDate(1),
        time: '10:00',
        location: '貴船',
        notes: '{"text":"縁結びの神社。新緑と桜のコントラスト"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '哲学の道散歩',
        date: getDate(1),
        time: '14:00',
        location: '左京区',
        notes: '{"text":"桜のトンネルを歩く"}',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: false,
      offset_minutes: 30,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: 'https://walica.jp/group/01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
