import { type DemoDataSet, now, getTimestamp, getEndTimestamp } from '../../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '春休みの京都旅行',
      theme_id: 'standard-spring',
      memo: '{"text":"桜シーズンは混雑するので早めの行動を！\\n\\n持ち物リスト\\n- カメラ\\n- 日焼け止め"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '清水寺参拝',
        start_at: getTimestamp(0, '09:00'),
        end_at: getEndTimestamp(getTimestamp(0, '09:00'), 120),
        location: '京都市東山区',
        notes: '{"text":"桜の名所。清水の舞台からの眺めは絶景。"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: '祇園で懐石料理',
        start_at: getTimestamp(0, '12:00'),
        end_at: getEndTimestamp(getTimestamp(0, '12:00'), 90),
        location: '祇園',
        notes: '{"text":"京料理を堪能"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '嵐山の桜散策',
        start_at: getTimestamp(0, '15:00'),
        end_at: getEndTimestamp(getTimestamp(0, '15:00'), 180),
        location: '嵐山',
        notes: '{"text":"竹林の小径と渡月橋を歩く"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '貴船神社の川沿い歩き',
        start_at: getTimestamp(1, '10:00'),
        end_at: getEndTimestamp(getTimestamp(1, '10:00'), 120),
        location: '貴船',
        notes: '{"text":"縁結びの神社。新緑と桜のコントラスト"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '哲学の道散歩',
        start_at: getTimestamp(1, '14:00'),
        end_at: getEndTimestamp(getTimestamp(1, '14:00'), 90),
        location: '左京区',
        notes: '{"text":"桜のトンネルを歩く"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-6',
        itinerary_id: 'demo',
        title: '伏見稲荷大社',
        start_at: getTimestamp(2, '09:00'),
        end_at: getEndTimestamp(getTimestamp(2, '09:00'), 150),
        location: '伏見区',
        notes: '{"text":"千本鳥居を散策"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-7',
        itinerary_id: 'demo',
        title: '宇治の平等院鳳凰堂',
        start_at: getTimestamp(2, '13:00'),
        end_at: getEndTimestamp(getTimestamp(2, '13:00'), 120),
        location: '宇治市',
        notes: '{"text":"世界遺産を訪問。抹茶スイーツも楽しむ"}',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 720,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: '01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
