import { type DemoDataSet, now, getDate } from '../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '世界の夜景フライト',
      theme_id: 'mapbox-journey',
      memo: '{"text":"グローブで航路をたどる旅"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '羽田を離陸',
        date: getDate(0),
        time: '07:30',
        location: '東京 (HND)',
        notes: '{"text":"朝焼けのなかで出発"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: '台北の街歩き',
        date: getDate(0),
        time: '11:30',
        location: '台北101',
        notes: '{"text":"鼎泰豊でランチ"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '夜市でライトアップ',
        date: getDate(0),
        time: '19:30',
        location: '士林夜市',
        notes: '{"text":"小籠包とマンゴーかき氷"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: 'グローブで航路確認',
        date: getDate(1),
        time: '08:00',
        location: '太平洋上空',
        notes: '{"text":"次の都市までのルートを可視化"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: 'サンセットフライト',
        date: getDate(1),
        time: '18:00',
        location: 'シンガポール上空',
        notes: '{"text":"マリーナベイの光を一望"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-6',
        itinerary_id: 'demo',
        title: 'リバークルーズ',
        date: getDate(1),
        time: '20:30',
        location: 'クラークキー',
        notes: '{"text":"夜景を眺めながら散歩"}',
        created_at: now,
        updated_at: now,
      },
    ],
  };
}
