import { type DemoDataSet, now, getTimestamp, getEndTimestamp } from '../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '京都紅葉旅行',
      theme_id: 'standard-autumn',
      memo: '{"text":"紅葉シーズンは混雑するので早めの行動を"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '清水寺',
        start_at: getTimestamp(0, '09:00'),
        end_at: getEndTimestamp(getTimestamp(0, '09:00'), 120),
        location: '京都市東山区',
        notes: '{"text":"紅葉の名所。朝早めがおすすめ。"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: '祇園でランチ',
        start_at: getTimestamp(0, '12:00'),
        end_at: getEndTimestamp(getTimestamp(0, '12:00'), 90),
        location: '祇園',
        notes: '{"text":"京料理を堪能"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: '嵐山散策',
        start_at: getTimestamp(0, '15:00'),
        end_at: getEndTimestamp(getTimestamp(0, '15:00'), 180),
        location: '嵐山',
        notes: '{"text":"竹林の小径を歩く"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '金閣寺',
        start_at: getTimestamp(1, '10:00'),
        end_at: getEndTimestamp(getTimestamp(1, '10:00'), 90),
        location: '北区',
        notes: '{"text":""}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '錦市場',
        start_at: getTimestamp(1, '13:00'),
        end_at: getEndTimestamp(getTimestamp(1, '13:00'), 120),
        location: '中京区',
        notes: '{"text":"食べ歩き！"}',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 30,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: 'https://walica.jp/group/01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
