import { type DemoDataSet, now, getTimestamp, getEndTimestamp } from '../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '沖縄リゾート',
      theme_id: 'ai-generated',
      memo: '{"text":"サプライズ旅行の計画"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '那覇空港到着',
        start_at: getTimestamp(0, '10:00'),
        end_at: getEndTimestamp(getTimestamp(0, '10:00'), 60),
        location: '那覇空港',
        notes: '{"text":"レンタカーを借りる"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: '美ら海水族館',
        start_at: getTimestamp(0, '13:00'),
        end_at: getEndTimestamp(getTimestamp(0, '13:00'), 240),
        location: '本部町',
        notes: '{"text":"ジンベエザメを見る！"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: 'ビーチでサンセット',
        start_at: getTimestamp(0, '18:00'),
        end_at: getEndTimestamp(getTimestamp(0, '18:00'), 60),
        location: '恩納村',
        notes: '{"text":""}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '🎁 サプライズディナー',
        start_at: getTimestamp(0, '19:30'),
        end_at: getEndTimestamp(getTimestamp(0, '19:30'), 120),
        location: 'オーシャンビューレストラン',
        notes: '{"text":"Secret: 特別なプロポーズディナー"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '国際通り散策',
        start_at: getTimestamp(1, '11:00'),
        end_at: getEndTimestamp(getTimestamp(1, '11:00'), 180),
        location: '那覇市',
        notes: '{"text":"お土産を買う"}',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 720,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: '01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
