import { type DemoDataSet, now, getDate } from '../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '沖縄リゾート',
      theme_id: 'ai-generated',
      memo: '{"text":"サプライズ旅行の計画"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '那覇空港到着',
        date: getDate(0),
        time: '10:00',
        location: '那覇空港',
        notes: '{"text":"レンタカーを借りる"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: '美ら海水族館',
        date: getDate(0),
        time: '13:00',
        location: '本部町',
        notes: '{"text":"ジンベエザメを見る！"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: 'ビーチでサンセット',
        date: getDate(0),
        time: '18:00',
        location: '恩納村',
        notes: '{"text":""}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: '🎁 サプライズディナー',
        date: getDate(0),
        time: '19:30',
        location: 'オーシャンビューレストラン',
        notes: '{"text":"Secret: 特別なプロポーズディナー"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '国際通り散策',
        date: getDate(1),
        time: '11:00',
        location: '那覇市',
        notes: '{"text":"お土産を買う"}',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 60,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: '01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
