import { type DemoDataSet, now, getTimestamp, getEndTimestamp } from '../../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '夏休みの沖縄旅行',
      theme_id: 'standard-summer',
      memo: '{"text":"真夏の沖縄！水分補給をこまめに\\n\\n持ち物リスト\\n- 水着\\n- 日焼け止め\\n- サングラス\\n- 帽子"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      // 終日イベント（海開きフェス）
      {
        id: 'demo-step-allday',
        itinerary_id: 'demo',
        title: 'エイサー祭り（終日）',
        start_at: getTimestamp(0, '00:00'),
        end_at: getTimestamp(0, '23:59'),
        location: '那覇市国際通り',
        notes: '{"text":"一日中沖縄の伝統芸能エイサーを楽しめる"}',
        is_all_day: true,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '那覇空港到着',
        start_at: getTimestamp(0, '10:00'),
        end_at: getEndTimestamp(getTimestamp(0, '10:00'), 60),
        location: '那覇市',
        notes: '{"text":"レンタカーを借りて出発！"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-1-transport',
        itinerary_id: 'demo',
        title: '空港からビーチへ移動',
        start_at: getTimestamp(0, '11:15'),
        end_at: getEndTimestamp(getTimestamp(0, '11:15'), 90),
        location: '恩納村へ移動',
        notes: '{"text":"レンタカーでの移動を想定"}',
        type: 'transport:car',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: 'ビーチでシュノーケリング',
        start_at: getTimestamp(0, '14:00'),
        end_at: getEndTimestamp(getTimestamp(0, '14:00'), 180),
        location: '恩納村',
        notes: '{"text":"青い海でカラフルな魚を見る"}',
        type: 'normal:sightseeing',
        created_at: now,
        updated_at: now,
      },
      // 複数日イベント（リゾートホテル宿泊）
      {
        id: 'demo-step-hotel',
        itinerary_id: 'demo',
        title: '恩納村リゾートホテル宿泊',
        start_at: getTimestamp(0, '19:00'),
        end_at: getTimestamp(1, '08:30'),
        location: '恩納村',
        notes: '{"text":"オーシャンビューのリゾートホテル。朝食とプール付き"}',
        type: 'normal:hotel',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: 'やちむん（陶芸）体験',
        start_at: getTimestamp(1, '10:00'),
        end_at: getEndTimestamp(getTimestamp(1, '10:00'), 120),
        location: '読谷村',
        notes: '{"text":"沖縄の伝統陶器を作る"}',
        type: 'normal:sightseeing',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-lunch',
        itinerary_id: 'demo',
        title: 'タコライス＆ソーキそば',
        start_at: getTimestamp(1, '12:30'),
        end_at: getEndTimestamp(getTimestamp(1, '12:30'), 60),
        location: '北谷町',
        notes: '{"text":"沖縄グルメを堪能"}',
        type: 'normal:meal',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: 'グラスボート',
        start_at: getTimestamp(1, '14:00'),
        end_at: getEndTimestamp(getTimestamp(1, '14:00'), 90),
        location: '恩納村',
        notes: '{"text":"海底のサンゴ礁を観察"}',
        type: 'normal:sightseeing',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-transport2',
        itinerary_id: 'demo',
        title: '恩納村から首里城へ移動',
        start_at: getTimestamp(2, '09:00'),
        end_at: getEndTimestamp(getTimestamp(2, '09:00'), 60),
        location: '那覇市へ移動',
        notes: '{"text":"最終日の観光スポットへ"}',
        type: 'transport:car',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '首里城見学',
        start_at: getTimestamp(2, '10:00'),
        end_at: getEndTimestamp(getTimestamp(2, '10:00'), 150),
        location: '那覇市',
        notes: '{"text":"琉球王国の歴史を学ぶ"}',
        type: 'normal:sightseeing',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-breakfast',
        itinerary_id: 'demo',
        title: 'ホテルの朝食ブッフェ',
        start_at: getTimestamp(1, '08:30'),
        end_at: getEndTimestamp(getTimestamp(1, '08:30'), 45),
        location: '恩納村',
        notes: '{"text":"リゾートホテル宿泊時の朝食"}',
        type: 'normal:meal',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-concurrent1',
        itinerary_id: 'demo',
        title: 'アクティビティ：バナナボート',
        start_at: getTimestamp(0, '14:00'),
        end_at: getEndTimestamp(getTimestamp(0, '14:00'), 90),
        location: '恩納村',
        notes: '{"text":"スリル満点のマリンスポーツ"}',
        type: 'normal:sightseeing',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-concurrent2',
        itinerary_id: 'demo',
        title: '別プラン：自由時間・荷物整理',
        start_at: getTimestamp(0, '14:00'),
        end_at: getEndTimestamp(getTimestamp(0, '14:00'), 120),
        location: '恩納村',
        notes: '{"text":"ビーチでのんびり過ごす"}',
        type: 'normal:sightseeing',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-exit',
        itinerary_id: 'demo',
        title: '那覇空港から帰路',
        start_at: getTimestamp(2, '16:00'),
        end_at: getEndTimestamp(getTimestamp(2, '16:00'), 120),
        location: '那覇空港',
        notes: '{"text":"帰宅便出発"}',
        type: 'transport:plane',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 720,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: '01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
