import { type DemoDataSet, now, getDate } from '../../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '夏休みの沖縄旅行',
      theme_id: 'standard-summer',
      memo: '{"text":"真夏の沖縄！水分補給をこまめに\\n\\n持ち物リスト\\n- 水着\\n- 日焼け止め\\n- サングラス"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '那覇空港到着',
        date: getDate(0),
        time: '10:00',
        location: '那覇市',
        notes: '{"text":"レンタカーを借りて出発！"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: 'ビーチでシュノーケリング',
        date: getDate(0),
        time: '14:00',
        location: '恩納村',
        notes: '{"text":"青い海でカラフルな魚を見る"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: 'やちむん（陶芸）体験',
        date: getDate(1),
        time: '10:00',
        location: '読谷村',
        notes: '{"text":"沖縄の伝統陶器を作る"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: 'グラスボート',
        date: getDate(1),
        time: '14:00',
        location: '恩納村',
        notes: '{"text":"海底のサンゴ礁を観察"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '首里城見学',
        date: getDate(2),
        time: '10:00',
        location: '那覇市',
        notes: '{"text":"琉球王国の歴史を学ぶ"}',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 60,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: '01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
