import { type DemoDataSet, now, getTimestamp, getEndTimestamp } from '../../types';

export function getDemoData(): DemoDataSet {
  return {
    itinerary: {
      id: 'demo',
      title: '夏休みの沖縄旅行',
      theme_id: 'standard-summer',
      memo: '{"text":"真夏の沖縄！水分補給をこまめに\\n\\n持ち物リスト\\n- 水着\\n- 日焼け止め\\n- サングラス"}',
      password: null,
      created_at: now,
      updated_at: now,
    },
    steps: [
      {
        id: 'demo-step-1',
        itinerary_id: 'demo',
        title: '那覇空港到着',
        start_at: getTimestamp(0, '10:00'),
        end_at: getEndTimestamp(getTimestamp(0, '10:00'), 60),
        location: '那覇市',
        notes: '{"text":"レンタカーを借りて出発！"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-1-transport',
        itinerary_id: 'demo',
        title: '空港からビーチへ移動',
        start_at: getTimestamp(0, '11:15'),
        end_at: getEndTimestamp(getTimestamp(0, '11:15'), 90),
        location: '恩納村へ移動',
        notes: '{"text":"レンタカーでの移動を想定"}',
        type: 'transport:car',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-2',
        itinerary_id: 'demo',
        title: 'ビーチでシュノーケリング',
        start_at: getTimestamp(0, '14:00'),
        end_at: getEndTimestamp(getTimestamp(0, '14:00'), 180),
        location: '恩納村',
        notes: '{"text":"青い海でカラフルな魚を見る"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-3',
        itinerary_id: 'demo',
        title: 'やちむん（陶芸）体験',
        start_at: getTimestamp(1, '10:00'),
        end_at: getEndTimestamp(getTimestamp(1, '10:00'), 120),
        location: '読谷村',
        notes: '{"text":"沖縄の伝統陶器を作る"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-4',
        itinerary_id: 'demo',
        title: 'グラスボート',
        start_at: getTimestamp(1, '14:00'),
        end_at: getEndTimestamp(getTimestamp(1, '14:00'), 90),
        location: '恩納村',
        notes: '{"text":"海底のサンゴ礁を観察"}',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'demo-step-5',
        itinerary_id: 'demo',
        title: '首里城見学',
        start_at: getTimestamp(2, '10:00'),
        end_at: getEndTimestamp(getTimestamp(2, '10:00'), 150),
        location: '那覇市',
        notes: '{"text":"琉球王国の歴史を学ぶ"}',
        created_at: now,
        updated_at: now,
      },
    ],
    itinerary_secrets: {
      itinerary_id: 'demo',
      enabled: true,
      offset_minutes: 720,
      created_at: now,
      updated_at: now,
    },
    itinerary_walica_settings: {
      itinerary_id: 'demo',
      walica_id: '01KBTSYADVKY8HPQ1CHRHTNG19',
      created_at: now,
      updated_at: now,
    },
  };
}
